### ISSUE TITLE
提交的备注都会多出"remark="

### ISSUE THREAD

**Issue by slain01** [MoonBegonia/ninja#10]
测试了下，把user.js这里改成直接传值就没问题了
const remarks = this.remark;
![image](https://user-images.githubusercontent.com/43878954/127337825-670caae8-3fb0-4d82-a255-fc28dcd88771.png)

**Comment by MoonBegonia** [comment]
![IMG_20210728_232412](https://user-images.githubusercontent.com/26798347/127350133-5d521053-ee52-4841-9743-cf6202adb988.jpg)
