### ISSUE TITLE
大佬，扫码问题

### ISSUE THREAD

**Issue by happy-happ** [MoonBegonia/ninja#33]
就是我在容器内执行了：
git clone https://github.com/MoonBegonia/ninja.git /ql/ninja
cd /ql/ninja/backend
pnpm install
pm2 start
cp sendNotify.js /ql/scripts/sendNotify.js

然后我端口映射的是80，我也在
cd /ql/ninja/backend
cp .env.example .env
vi .env这里更改了80
pm2 start也启动了
但是打不开80端口，我也放行80的，老哥求解

**Comment by timessage** [comment]
改端口

**Comment by happy-happ** [comment]
> 改端口
80的端口不行吗

**Comment by mzljjkj** [comment]
用80！！！！！！你怎么想的 你用880吧
