### ISSUE TITLE
京东扫码登录后，push.jpg问题

### ISSUE THREAD

**Issue by wxuuu** [MoonBegonia/ninja#35]
`自定义推送二维码：将 push.jpg 文件添加到 /ql/ninja/backend/static/ 目录下刷新网页即可。  

自定义常见活动：修改 /ql/backend/static/activity.json 即可`

按照readme，配置好push.jpg文件到` /ql/ninja/backend/static/`文件夹，但是并不会出现二维码，还是之前上传到服务器文件夹的原文件。

![捕获.PNG](https://i.loli.net/2021/08/10/rYSDOeHhsP1bE37.png)

**请教大佬**

**Comment by ylwzbk** [comment]
重新 启动就行了

**Comment by wxuuu** [comment]
重启也还是一样

**Comment by wxuuu** [comment]
> 重新 启动就行了

重启也还是一样

**Comment by ylwzbk** [comment]
还有缓存清理一下 ， 你换其他浏览器查看就知道了

**Comment by wxuuu** [comment]
> 还有缓存清理一下 ， 你换其他浏览器查看就知道了

清缓存，换浏览器，还是一样😫😫😫

**Comment by juren8848** [comment]
同问，我也是点扫描二维码登陆二维码图片出不来，不知道哪里设置不对

**Comment by wq5011** [comment]
这个“自定义推送二维码”是什么意思啊？哪位大佬解释下。
青龙里面有多个cookie,能不能实现用ninja登录获取cookie后，再设置每个cookie跑完脚本后的推送通知，不然，所有的推送通知都在一起。
这个“自定义推送二维码”是实现这个的吗？
另外 push.jpg在哪啊？
