### ISSUE TITLE
扫码页面浏览器正常模式不能多账号录入

### ISSUE THREAD

**Issue by KMJ-2020** [MoonBegonia/ninja#40]
希望作者能看到，在浏览器正常模式下扫码或者跳转京东登录后，保存完ck，关闭网页退出浏览器，再次打开扫码网页，还会保留在扫完码的页面，只能删除或者退出账号才能操作下一个账号，这样就不能多账号了，目前只能用无痕方式打开扫码网页或者正常模式下，清除一下浏览器数据才能加入多个ck，希望作者能够修复一下，谢谢

**Comment by ylwzbk** [comment]
就是这样设计的，不算bug

**Comment by KMJ-2020** [comment]
> 就是这样设计的，不算bug

谢谢，尝试了一下，确实可以
