### ISSUE TITLE
青龙2.8.2无法登陆

### ISSUE THREAD

**Issue by siyue666** [MoonBegonia/ninja#42]
大佬能适配一下青龙2.8.2吗

**Comment by mzljjkj** [comment]
rm -rf /root/ql/ninja/backend/ql.js  &&   rm -rf /root/ql/ninja/backend/user.js. &&  cd ql/ninja/backend &&  wget  https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js &&  https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js

**Comment by siyue666** [comment]
> rm -rf /root/ql/ninja/backend/ql.js && rm -rf /root/ql/ninja/backend/user.js && cd ql/ninja/backend && wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js && wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js

2.8.3又不能用了

**Comment by kelejuan77** [comment]
这个是直接在用shell连接服务器，输入三次这个命令就可以了么
> rm -rf /root/ql/ninja/backend/ql.js  &&   rm -rf /root/ql/ninja/backend/user.js &&  cd ql/ninja/backend &&  wget  https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js &&  wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
