### ISSUE TITLE
大佬 跪求更新啊 适配新版青龙2.8

### ISSUE THREAD

**Issue by prcxu** [MoonBegonia/ninja#43]
大佬 跪求更新啊 适配新版青龙2.8

**Comment by 1768666368** [comment]
pr里有更新了呀，改一下就好了

**Comment by mzljjkj** [comment]
rm -rf /root/ql/ninja/backend/ql.js  &&   rm -rf /root/ql/ninja/backend/user.js. &&  cd ql/ninja/backend &&  wget  https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js &&  https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
