### ISSUE TITLE
点击登入后无反应

### ISSUE THREAD

**Issue by Zhangjai** [MoonBegonia/ninja#46]
尝试两种方法登入后网页都没有反应，然后那个余量也没有减少，是什么原因呢？？

**Comment by littleCareless** [comment]
目前青龙2.8.2 不支持

**Comment by gold2wave** [comment]
我也遇到了，提示token不存在

**Comment by teg1c** [comment]
青龙2.8.2 添加环境变量修改了逻辑，所以这边也不行

**Comment by Zhangjai** [comment]
搞晚了，早点去搞就没事了，刚进TG看到大佬的通知

**Comment by littleCareless** [comment]
pr里面有更新 自己改下吧

**Comment by kelejuan77** [comment]
> pr里面有更新 自己改下吧 

怎么更新的，有具体操作吗，小白不怎么懂
