### ISSUE TITLE
能否新增调用青龙的通知

### ISSUE THREAD

**Issue by SNAKEXGC** [MoonBegonia/ninja#5]
再有人扫码登录，或者删除ck等操作后，通过青龙配置的通知推送，或者自己设置一个推送配置的地方，希望大佬采纳！

**Comment by cutecat1314** [comment]
打赏肯定有

**Comment by SNAKEXGC** [comment]
> 你打赏说不定有

有，只是我之前配置错了，现在就有，删帖了，抱歉，打扰作者了！
