### ISSUE TITLE
兼容青龙2.8.3版本：https://github.com/yizhiyan/ninja_next

### ISSUE THREAD

**Issue by yizhiyan** [MoonBegonia/ninja#50]
兼容青龙2.8.3版本：https://github.com/yizhiyan/ninja_next

**Comment by littleCareless** [comment]
> 兼容青龙2.8.3版本：https://github.com/yizhiyan/ninja_next

啊这

**Comment by fyn130** [comment]
好像还是不行

**Comment by bcfxclub** [comment]
> 好像还是不行

在配置文件extra.sh里面删掉原来的命令，临时替换为
cd /ql/ninja/backend
git checkout .
git pull
rm -rf ql.js
rm -rf user.js
wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js
wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
pnpm install
pm2 start

重启青龙面板，等待程序完全运行起来。我是这样解决的现在2.8.3-001。这两组命令“rm -rf /root/ql/ninja/backend/ql.js && rm -rf /root/ql/ninja/backend/user.js. ”在我这里不好用文件没有被删除或者修改，所有我改成目录内直接操作文件了

**Comment by AU-Linsanity** [comment]
还是不行....

**Comment by z919126592** [comment]
> > 好像还是不行
> 
> 在配置文件extra.sh里面删掉原来的命令，临时替换为
> cd /ql/ninja/backend
> git checkout .
> git pull
> rm -rf ql.js
> rm -rf user.js
> wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js
> wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
> pnpm install
> pm2 start
> 
> 重启青龙面板，等待程序完全运行起来。我是这样解决的现在2.8.3-001。这两组命令“rm -rf /root/ql/ninja/backend/ql.js && rm -rf /root/ql/ninja/backend/user.js. ”在我这里不好用文件没有被删除或者修改，所有我改成目录内直接操作文件了

亲测有效

**Comment by kingchaoliang** [comment]
> > > 好像还是不行
> > 
> > 
> > 在配置文件extra.sh里面删掉原来的命令，临时替换为
> > cd /ql/ninja/backend
> > git checkout .
> > git pull
> > rm -rf ql.js
> > rm -rf user.js
> > wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js
> > wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
> > pnpm install
> > pm2 start
> > 重启青龙面板，等待程序完全运行起来。我是这样解决的现在2.8.3-001。这两组命令“rm -rf /root/ql/ninja/backend/ql.js && rm -rf /root/ql/ninja/backend/user.js. ”在我这里不好用文件没有被删除或者修改，所有我改成目录内直接操作文件了
> 
> 亲测有效

能远程帮处理一下吗？我试过还是不行

**Comment by shikkoku** [comment]
用了楼主的源的确修好了……2.8.4可用。

**Comment by boliliu** [comment]
> > 好像还是不行
> 
> 在配置文件extra.sh里面删掉原来的命令，临时替换为
> cd /ql/ninja/backend
> git checkout .
> git pull
> rm -rf ql.js
> rm -rf user.js
> wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/ql.js
> wget https://ghproxy.com/https://raw.githubusercontent.com/MoonBegonia/ninja/deda6f0c0207f2bc0e10454fdbe99b3a9f3878a8/backend/user.js
> pnpm install
> pm2 start
> 
> 重启青龙面板，等待程序完全运行起来。我是这样解决的现在2.8.3-001。这两组命令“rm -rf /root/ql/ninja/backend/ql.js && rm -rf /root/ql/ninja/backend/user.js. ”在我这里不好用文件没有被删除或者修改，所有我改成目录内直接操作文件了

求原来的命令

**Comment by MoonBegonia** [comment]
此项目存在盗CK嫌疑，已LOCK。
