### ISSUE TITLE
青龙2.8.1+ninja，端口修改不成功

### ISSUE THREAD

**Issue by TZbeyond** [MoonBegonia/ninja#52]
尝试在宝塔面板将example里得端口号5701改为2052（因cloud flare不代理5701，可代理2052），然后在终端运行
sudo docker exec -it qinglong bash 
cd /ql/ninja/backend
cp .env.example .env
vi .env
pm2 start
然后执行extra.sh
无效，IP:5701不可以访问，IP:2052无法访问，此时.env已更改
尝试直接在宝塔面板里，修改.env里人数上限，重复后面步骤，修改成功，
再次修改端口号，重复后面步骤，不成功，此时扫描端口发现5701和2052都没开，但可以确定得是我的谷歌云服务器防火墙规则为所有端口都打开了

**Comment by MoonBegonia** [comment]
外部端口建议改 docker 映射端口而不是 ninja 内部端口
