### ISSUE TITLE
青龙2.8.4版本不能登录

### ISSUE THREAD

**Issue by minecraftlight** [MoonBegonia/ninja#54]
有二维码，扫描完手机JD弹窗提示“请升级到最新版本的手机JD”
然后网页也没有跳转，余量也不会减少
青龙面板也没有新增变量

**Comment by minecraftlight** [comment]
还有就是手机JD是最新的版本了

**Comment by lancer-wang** [comment]
我的连二维码都没,2.8.4-004版本

**Comment by yakun0622** [comment]
> 我的连二维码都没,2.8.4-004版本

+1

**Comment by minecraftlight** [comment]
> 我的连二维码都没,2.8.4-004版本

我现在也没有了😂😂

**Comment by NBlackQIE** [comment]
我的也没有二维码了
