### ISSUE TITLE
jwt令牌问题

### ISSUE THREAD

**Issue by lonelyman0108** [MoonBegonia/ninja#57]
ninja页面打开时会请求青龙的api，例如`api/envs`，每一此调用都需要jwt令牌

https://github.com/MoonBegonia/ninja/blob/52ee4774de6233df97ecdd92ee76c3133ebe7947/backend/ql.js#L31

这个令牌是从青龙的auth.json里面读取的，这一步都没啥问题
但是如果管理员退出登录了青龙，就会直接清空jwt令牌

https://github.com/whyour/qinglong/blob/be4e1001684ebec049cb9495f367abf5a5ae2502/back/api/auth.ts#L47

再让ninja去调用api的时候就会失败
解决方法就是管理员登录青龙后不能logout，直接关闭窗口才行
而且因为jwt令牌的有效期是三天

https://github.com/whyour/qinglong/blob/82880c3f06ba9e3532e265adea927a5c55d2ddca/back/services/auth.ts#L56

还需要每隔三天就重新登陆一次

这应该算是一个bug吧，希望能修复下

**Comment by MoonBegonia** [comment]
青龙不支持多点登录，当初采用了这种方式，如果用用户名密码自己获取 token 就会和 xdd 一样和用户抢登录状态，没有完美的解决方案，很难受。

**Comment by lonelyman0108** [comment]
> 青龙不支持多点登录，当初采用了这种方式，如果用用户名密码自己获取 token 就会和 xdd 一样和用户抢登录状态，没有完美的解决方案，很难受。

青龙里面应该可以改axios的处理方式吧，对来源是ninja的直接开放应该就没啥问题了吧
反正在同一局域网内

**Comment by MoonBegonia** [comment]
> > 青龙不支持多点登录，当初采用了这种方式，如果用用户名密码自己获取 token 就会和 xdd 一样和用户抢登录状态，没有完美的解决方案，很难受。
> 
> 青龙里面应该可以改axios的处理方式吧，对来源是ninja的直接开放应该就没啥问题了吧
> 反正在同一局域网内

让青龙正确使用 jwt 支持多点登录不是更好

**Comment by lonelyman0108** [comment]
> > > 青龙不支持多点登录，当初采用了这种方式，如果用用户名密码自己获取 token 就会和 xdd 一样和用户抢登录状态，没有完美的解决方案，很难受。
> > 
> > 
> > 青龙里面应该可以改axios的处理方式吧，对来源是ninja的直接开放应该就没啥问题了吧
> > 反正在同一局域网内
> 
> 让青龙正确使用 jwt 支持多点登录不是更好

也是，那就这样吧，也没啥能解决的方案了，不过我看电报群有人就遇到了这个问题，还不知道到咋整

**Comment by littleCareless** [comment]
> 青龙不支持多点登录，当初采用了这种方式，如果用用户名密码自己获取 token 就会和 xdd 一样和用户抢登录状态，没有完美的解决方案，很难受。

蓝受
