### ISSUE TITLE
我的也没有二维码了

### ISSUE THREAD

**Issue by hehe036** [MoonBegonia/ninja#59]
我的也没有二维码了

_Originally posted by @NBlackQIE in https://github.com/MoonBegonia/ninja/issues/54#issuecomment-904398908_

**Comment by sorry510** [comment]
我的也是，点击扫描二维码登陆，没有反应了

**Comment by shyg866** [comment]
我的也是，点击扫描二维码登陆，没有反应了

**Comment by shyg866** [comment]
希望大佬及时修复啊

**Comment by DingChang90** [comment]
https://raw.githubusercontent.com/Oreomeow/VIP/main/Conf/Qinglong/Ninja/.env
更新一下配置，增加UA就可以用了
