### ISSUE TITLE
2.8.5 和2.9无法添加新用户

### ISSUE THREAD

**Issue by aibeso** [MoonBegonia/ninja#64]
老用户扫码更新cookie可正常使用，新用户可以扫码无法添加到qinglong面板
调试新版本qinglong新增cookie的api接口：“api/envs” ，body是这样的： [{value: "dfsdfsdfsdfsdfs", name: "JD_COOKIE"}]
调试ninja扫码登陆部分，使用新用户扫码 可以输出扫码后的cookie
ql.js文件的代码新增部分代码（addEnv方法）：
    method: 'post',
    url: 'api/envs',
    params: { t: Date.now() },
    json: {
      name: 'JD_COOKIE',
      value: cookie,
      remarks,
    },
是否是因为“api/envs”这接口的改变导致的新版本无法使用？

**Comment by ufxymsn** [comment]
我也碰上这个问题了，新用户无法添加！

**Comment by littleCareless** [comment]
> 老用户扫码更新cookie可正常使用，新用户可以扫码无法添加到qinglong面板
> 调试新版本qinglong新增cookie的api接口：“api/envs” ，body是这样的： [{value: "dfsdfsdfsdfsdfs", name: "JD_COOKIE"}]
> 调试ninja扫码登陆部分，使用新用户扫码 可以输出扫码后的cookie
> ql.js文件的代码新增部分代码（addEnv方法）：
> method: 'post',
> url: 'api/envs',
> params: { t: Date.now() },
> json: {
> name: 'JD_COOKIE',
> value: cookie,
> remarks,
> },
> 是否是因为“api/envs”这接口的改变导致的新版本无法使用？

....新版已经更新了啊emm

**Comment by webfamer** [comment]
挂了，大佬能更新下吗

**Comment by Limaoda** [comment]
无法打开登录二维码了，大佬更新下咯

**Comment by aibeso** [comment]
刚刚试了一下又可以了

**Comment by Limaoda** [comment]
> 刚试又可以了

我的现在更新到2.9显示不了二维码登录是什么问题？
