### ISSUE TITLE
通过页面扫码或者跳转登陆时会提示账号风险

### ISSUE THREAD

**Issue by lanyugod** [MoonBegonia/ninja#68]
页面会有提示：您的账号存在风险，请您稍后再试或联系客服
无法通过扫码或者跳转app登录

**Comment by iamvicliu** [comment]
![image](https://user-images.githubusercontent.com/8925514/145700569-bb2e7979-c768-482f-a7ef-0617f7b6af6b.png)


我也是这样的提示

**Comment by lanyugod** [comment]
> ![image](https://user-images.githubusercontent.com/8925514/145700569-bb2e7979-c768-482f-a7ef-0617f7b6af6b.png)
> 
> 我也是这样的提示

大概率是 和谐了等作者重构得吧

**Comment by iamvicliu** [comment]
嗯，现在只能手动写cookie了

**Comment by ctaoist** [comment]
估计是的了，刚开始玩，才试了JDC，然后转到这个，都不行，太难了

**Comment by lanyugod** [comment]
>
